/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidateIndexRouteImport } from './routes/validate/index'
import { Route as TrainIndexRouteImport } from './routes/train/index'
import { Route as SubdatasetsIndexRouteImport } from './routes/subdatasets/index'
import { Route as PretrainedModelsIndexRouteImport } from './routes/pretrained-models/index'
import { Route as PresetsIndexRouteImport } from './routes/presets/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ArchitecturesIndexRouteImport } from './routes/architectures/index'
import { Route as ValidateCreateRouteImport } from './routes/validate/create'
import { Route as ValidateTaskIdRouteImport } from './routes/validate/$taskId'
import { Route as TrainCreateRouteImport } from './routes/train/create'
import { Route as TrainTaskIdRouteImport } from './routes/train/$taskId'
import { Route as SystemUserRouteImport } from './routes/system/user'
import { Route as SubdatasetsCreateRouteImport } from './routes/subdatasets/create'
import { Route as PretrainedModelsCreateRouteImport } from './routes/pretrained-models/create'
import { Route as PretrainedModelsModelIdRouteImport } from './routes/pretrained-models/$modelId'
import { Route as PresetsCreateRouteImport } from './routes/presets/create'
import { Route as PresetsPresetIdRouteImport } from './routes/presets/$presetId'
import { Route as ModelsManualUploadRouteImport } from './routes/models/manualUpload'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'
import { Route as ArchitecturesCreateRouteImport } from './routes/architectures/create'
import { Route as ArchitecturesArchitectureIdRouteImport } from './routes/architectures/$architectureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateIndexRoute = ValidateIndexRouteImport.update({
  id: '/validate/',
  path: '/validate/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainIndexRoute = TrainIndexRouteImport.update({
  id: '/train/',
  path: '/train/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubdatasetsIndexRoute = SubdatasetsIndexRouteImport.update({
  id: '/subdatasets/',
  path: '/subdatasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PretrainedModelsIndexRoute = PretrainedModelsIndexRouteImport.update({
  id: '/pretrained-models/',
  path: '/pretrained-models/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsIndexRoute = PresetsIndexRouteImport.update({
  id: '/presets/',
  path: '/presets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitecturesIndexRoute = ArchitecturesIndexRouteImport.update({
  id: '/architectures/',
  path: '/architectures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateCreateRoute = ValidateCreateRouteImport.update({
  id: '/validate/create',
  path: '/validate/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateTaskIdRoute = ValidateTaskIdRouteImport.update({
  id: '/validate/$taskId',
  path: '/validate/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainCreateRoute = TrainCreateRouteImport.update({
  id: '/train/create',
  path: '/train/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainTaskIdRoute = TrainTaskIdRouteImport.update({
  id: '/train/$taskId',
  path: '/train/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUserRoute = SystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SubdatasetsCreateRoute = SubdatasetsCreateRouteImport.update({
  id: '/subdatasets/create',
  path: '/subdatasets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PretrainedModelsCreateRoute = PretrainedModelsCreateRouteImport.update({
  id: '/pretrained-models/create',
  path: '/pretrained-models/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PretrainedModelsModelIdRoute = PretrainedModelsModelIdRouteImport.update({
  id: '/pretrained-models/$modelId',
  path: '/pretrained-models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsCreateRoute = PresetsCreateRouteImport.update({
  id: '/presets/create',
  path: '/presets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsPresetIdRoute = PresetsPresetIdRouteImport.update({
  id: '/presets/$presetId',
  path: '/presets/$presetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsManualUploadRoute = ModelsManualUploadRouteImport.update({
  id: '/models/manualUpload',
  path: '/models/manualUpload',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitecturesCreateRoute = ArchitecturesCreateRouteImport.update({
  id: '/architectures/create',
  path: '/architectures/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitecturesArchitectureIdRoute =
  ArchitecturesArchitectureIdRouteImport.update({
    id: '/architectures/$architectureId',
    path: '/architectures/$architectureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architectures/$architectureId': typeof ArchitecturesArchitectureIdRoute
  '/architectures/create': typeof ArchitecturesCreateRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/presets/$presetId': typeof PresetsPresetIdRoute
  '/presets/create': typeof PresetsCreateRoute
  '/pretrained-models/$modelId': typeof PretrainedModelsModelIdRoute
  '/pretrained-models/create': typeof PretrainedModelsCreateRoute
  '/subdatasets/create': typeof SubdatasetsCreateRoute
  '/system/user': typeof SystemUserRoute
  '/train/$taskId': typeof TrainTaskIdRoute
  '/train/create': typeof TrainCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/architectures/': typeof ArchitecturesIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/presets/': typeof PresetsIndexRoute
  '/pretrained-models/': typeof PretrainedModelsIndexRoute
  '/subdatasets/': typeof SubdatasetsIndexRoute
  '/train/': typeof TrainIndexRoute
  '/validate/': typeof ValidateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architectures/$architectureId': typeof ArchitecturesArchitectureIdRoute
  '/architectures/create': typeof ArchitecturesCreateRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/presets/$presetId': typeof PresetsPresetIdRoute
  '/presets/create': typeof PresetsCreateRoute
  '/pretrained-models/$modelId': typeof PretrainedModelsModelIdRoute
  '/pretrained-models/create': typeof PretrainedModelsCreateRoute
  '/subdatasets/create': typeof SubdatasetsCreateRoute
  '/system/user': typeof SystemUserRoute
  '/train/$taskId': typeof TrainTaskIdRoute
  '/train/create': typeof TrainCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/architectures': typeof ArchitecturesIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/presets': typeof PresetsIndexRoute
  '/pretrained-models': typeof PretrainedModelsIndexRoute
  '/subdatasets': typeof SubdatasetsIndexRoute
  '/train': typeof TrainIndexRoute
  '/validate': typeof ValidateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architectures/$architectureId': typeof ArchitecturesArchitectureIdRoute
  '/architectures/create': typeof ArchitecturesCreateRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/presets/$presetId': typeof PresetsPresetIdRoute
  '/presets/create': typeof PresetsCreateRoute
  '/pretrained-models/$modelId': typeof PretrainedModelsModelIdRoute
  '/pretrained-models/create': typeof PretrainedModelsCreateRoute
  '/subdatasets/create': typeof SubdatasetsCreateRoute
  '/system/user': typeof SystemUserRoute
  '/train/$taskId': typeof TrainTaskIdRoute
  '/train/create': typeof TrainCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/architectures/': typeof ArchitecturesIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/presets/': typeof PresetsIndexRoute
  '/pretrained-models/': typeof PretrainedModelsIndexRoute
  '/subdatasets/': typeof SubdatasetsIndexRoute
  '/train/': typeof TrainIndexRoute
  '/validate/': typeof ValidateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architectures/$architectureId'
    | '/architectures/create'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/manualUpload'
    | '/presets/$presetId'
    | '/presets/create'
    | '/pretrained-models/$modelId'
    | '/pretrained-models/create'
    | '/subdatasets/create'
    | '/system/user'
    | '/train/$taskId'
    | '/train/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/architectures/'
    | '/datasets/'
    | '/models/'
    | '/presets/'
    | '/pretrained-models/'
    | '/subdatasets/'
    | '/train/'
    | '/validate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architectures/$architectureId'
    | '/architectures/create'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/manualUpload'
    | '/presets/$presetId'
    | '/presets/create'
    | '/pretrained-models/$modelId'
    | '/pretrained-models/create'
    | '/subdatasets/create'
    | '/system/user'
    | '/train/$taskId'
    | '/train/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/architectures'
    | '/datasets'
    | '/models'
    | '/presets'
    | '/pretrained-models'
    | '/subdatasets'
    | '/train'
    | '/validate'
  id:
    | '__root__'
    | '/'
    | '/architectures/$architectureId'
    | '/architectures/create'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/manualUpload'
    | '/presets/$presetId'
    | '/presets/create'
    | '/pretrained-models/$modelId'
    | '/pretrained-models/create'
    | '/subdatasets/create'
    | '/system/user'
    | '/train/$taskId'
    | '/train/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/architectures/'
    | '/datasets/'
    | '/models/'
    | '/presets/'
    | '/pretrained-models/'
    | '/subdatasets/'
    | '/train/'
    | '/validate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitecturesArchitectureIdRoute: typeof ArchitecturesArchitectureIdRoute
  ArchitecturesCreateRoute: typeof ArchitecturesCreateRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ModelsManualUploadRoute: typeof ModelsManualUploadRoute
  PresetsPresetIdRoute: typeof PresetsPresetIdRoute
  PresetsCreateRoute: typeof PresetsCreateRoute
  PretrainedModelsModelIdRoute: typeof PretrainedModelsModelIdRoute
  PretrainedModelsCreateRoute: typeof PretrainedModelsCreateRoute
  SubdatasetsCreateRoute: typeof SubdatasetsCreateRoute
  SystemUserRoute: typeof SystemUserRoute
  TrainTaskIdRoute: typeof TrainTaskIdRoute
  TrainCreateRoute: typeof TrainCreateRoute
  ValidateTaskIdRoute: typeof ValidateTaskIdRoute
  ValidateCreateRoute: typeof ValidateCreateRoute
  ArchitecturesIndexRoute: typeof ArchitecturesIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  PresetsIndexRoute: typeof PresetsIndexRoute
  PretrainedModelsIndexRoute: typeof PretrainedModelsIndexRoute
  SubdatasetsIndexRoute: typeof SubdatasetsIndexRoute
  TrainIndexRoute: typeof TrainIndexRoute
  ValidateIndexRoute: typeof ValidateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/': {
      id: '/validate/'
      path: '/validate'
      fullPath: '/validate/'
      preLoaderRoute: typeof ValidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/': {
      id: '/train/'
      path: '/train'
      fullPath: '/train/'
      preLoaderRoute: typeof TrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subdatasets/': {
      id: '/subdatasets/'
      path: '/subdatasets'
      fullPath: '/subdatasets/'
      preLoaderRoute: typeof SubdatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretrained-models/': {
      id: '/pretrained-models/'
      path: '/pretrained-models'
      fullPath: '/pretrained-models/'
      preLoaderRoute: typeof PretrainedModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets/': {
      id: '/presets/'
      path: '/presets'
      fullPath: '/presets/'
      preLoaderRoute: typeof PresetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architectures/': {
      id: '/architectures/'
      path: '/architectures'
      fullPath: '/architectures/'
      preLoaderRoute: typeof ArchitecturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/create': {
      id: '/validate/create'
      path: '/validate/create'
      fullPath: '/validate/create'
      preLoaderRoute: typeof ValidateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/$taskId': {
      id: '/validate/$taskId'
      path: '/validate/$taskId'
      fullPath: '/validate/$taskId'
      preLoaderRoute: typeof ValidateTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/create': {
      id: '/train/create'
      path: '/train/create'
      fullPath: '/train/create'
      preLoaderRoute: typeof TrainCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$taskId': {
      id: '/train/$taskId'
      path: '/train/$taskId'
      fullPath: '/train/$taskId'
      preLoaderRoute: typeof TrainTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/user': {
      id: '/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof SystemUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subdatasets/create': {
      id: '/subdatasets/create'
      path: '/subdatasets/create'
      fullPath: '/subdatasets/create'
      preLoaderRoute: typeof SubdatasetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretrained-models/create': {
      id: '/pretrained-models/create'
      path: '/pretrained-models/create'
      fullPath: '/pretrained-models/create'
      preLoaderRoute: typeof PretrainedModelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretrained-models/$modelId': {
      id: '/pretrained-models/$modelId'
      path: '/pretrained-models/$modelId'
      fullPath: '/pretrained-models/$modelId'
      preLoaderRoute: typeof PretrainedModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets/create': {
      id: '/presets/create'
      path: '/presets/create'
      fullPath: '/presets/create'
      preLoaderRoute: typeof PresetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets/$presetId': {
      id: '/presets/$presetId'
      path: '/presets/$presetId'
      fullPath: '/presets/$presetId'
      preLoaderRoute: typeof PresetsPresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/manualUpload': {
      id: '/models/manualUpload'
      path: '/models/manualUpload'
      fullPath: '/models/manualUpload'
      preLoaderRoute: typeof ModelsManualUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architectures/create': {
      id: '/architectures/create'
      path: '/architectures/create'
      fullPath: '/architectures/create'
      preLoaderRoute: typeof ArchitecturesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architectures/$architectureId': {
      id: '/architectures/$architectureId'
      path: '/architectures/$architectureId'
      fullPath: '/architectures/$architectureId'
      preLoaderRoute: typeof ArchitecturesArchitectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitecturesArchitectureIdRoute: ArchitecturesArchitectureIdRoute,
  ArchitecturesCreateRoute: ArchitecturesCreateRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ModelsManualUploadRoute: ModelsManualUploadRoute,
  PresetsPresetIdRoute: PresetsPresetIdRoute,
  PresetsCreateRoute: PresetsCreateRoute,
  PretrainedModelsModelIdRoute: PretrainedModelsModelIdRoute,
  PretrainedModelsCreateRoute: PretrainedModelsCreateRoute,
  SubdatasetsCreateRoute: SubdatasetsCreateRoute,
  SystemUserRoute: SystemUserRoute,
  TrainTaskIdRoute: TrainTaskIdRoute,
  TrainCreateRoute: TrainCreateRoute,
  ValidateTaskIdRoute: ValidateTaskIdRoute,
  ValidateCreateRoute: ValidateCreateRoute,
  ArchitecturesIndexRoute: ArchitecturesIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  PresetsIndexRoute: PresetsIndexRoute,
  PretrainedModelsIndexRoute: PretrainedModelsIndexRoute,
  SubdatasetsIndexRoute: SubdatasetsIndexRoute,
  TrainIndexRoute: TrainIndexRoute,
  ValidateIndexRoute: ValidateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
