/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualIndexRouteImport } from './routes/visual/index'
import { Route as ValidateIndexRouteImport } from './routes/validate/index'
import { Route as TemplateIndexRouteImport } from './routes/template/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SquareIndexRouteImport } from './routes/square/index'
import { Route as SlicesIndexRouteImport } from './routes/slices/index'
import { Route as MonitorIndexRouteImport } from './routes/monitor/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as VisualModelIdRouteImport } from './routes/visual/$modelId'
import { Route as ValidateCreateRouteImport } from './routes/validate/create'
import { Route as ValidateTaskIdRouteImport } from './routes/validate/$taskId'
import { Route as TemplateCreateRouteImport } from './routes/template/create'
import { Route as TemplateTemplateIdRouteImport } from './routes/template/$templateId'
import { Route as TasksCreateRouteImport } from './routes/tasks/create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SystemUserRouteImport } from './routes/system/user'
import { Route as SquareCreateRouteImport } from './routes/square/create'
import { Route as SlicesCreateRouteImport } from './routes/slices/create'
import { Route as ModelsSquareRouteImport } from './routes/models/square'
import { Route as ModelsManualUploadRouteImport } from './routes/models/manualUpload'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualIndexRoute = VisualIndexRouteImport.update({
  id: '/visual/',
  path: '/visual/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateIndexRoute = ValidateIndexRouteImport.update({
  id: '/validate/',
  path: '/validate/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIndexRoute = TemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquareIndexRoute = SquareIndexRouteImport.update({
  id: '/square/',
  path: '/square/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlicesIndexRoute = SlicesIndexRouteImport.update({
  id: '/slices/',
  path: '/slices/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIndexRoute = MonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualModelIdRoute = VisualModelIdRouteImport.update({
  id: '/visual/$modelId',
  path: '/visual/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateCreateRoute = ValidateCreateRouteImport.update({
  id: '/validate/create',
  path: '/validate/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateTaskIdRoute = ValidateTaskIdRouteImport.update({
  id: '/validate/$taskId',
  path: '/validate/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateCreateRoute = TemplateCreateRouteImport.update({
  id: '/template/create',
  path: '/template/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateTemplateIdRoute = TemplateTemplateIdRouteImport.update({
  id: '/template/$templateId',
  path: '/template/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUserRoute = SystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SquareCreateRoute = SquareCreateRouteImport.update({
  id: '/square/create',
  path: '/square/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SlicesCreateRoute = SlicesCreateRouteImport.update({
  id: '/slices/create',
  path: '/slices/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSquareRoute = ModelsSquareRouteImport.update({
  id: '/models/square',
  path: '/models/square',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsManualUploadRoute = ModelsManualUploadRouteImport.update({
  id: '/models/manualUpload',
  path: '/models/manualUpload',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/models/square': typeof ModelsSquareRoute
  '/slices/create': typeof SlicesCreateRoute
  '/square/create': typeof SquareCreateRoute
  '/system/user': typeof SystemUserRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/template/create': typeof TemplateCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/visual/$modelId': typeof VisualModelIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/slices/': typeof SlicesIndexRoute
  '/square/': typeof SquareIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/template/': typeof TemplateIndexRoute
  '/validate/': typeof ValidateIndexRoute
  '/visual/': typeof VisualIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/models/square': typeof ModelsSquareRoute
  '/slices/create': typeof SlicesCreateRoute
  '/square/create': typeof SquareCreateRoute
  '/system/user': typeof SystemUserRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/template/create': typeof TemplateCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/visual/$modelId': typeof VisualModelIdRoute
  '/datasets': typeof DatasetsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/monitor': typeof MonitorIndexRoute
  '/slices': typeof SlicesIndexRoute
  '/square': typeof SquareIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/template': typeof TemplateIndexRoute
  '/validate': typeof ValidateIndexRoute
  '/visual': typeof VisualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/models/square': typeof ModelsSquareRoute
  '/slices/create': typeof SlicesCreateRoute
  '/square/create': typeof SquareCreateRoute
  '/system/user': typeof SystemUserRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/template/create': typeof TemplateCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/visual/$modelId': typeof VisualModelIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/slices/': typeof SlicesIndexRoute
  '/square/': typeof SquareIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/template/': typeof TemplateIndexRoute
  '/validate/': typeof ValidateIndexRoute
  '/visual/': typeof VisualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/manualUpload'
    | '/models/square'
    | '/slices/create'
    | '/square/create'
    | '/system/user'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/template/$templateId'
    | '/template/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/visual/$modelId'
    | '/datasets/'
    | '/models/'
    | '/monitor/'
    | '/slices/'
    | '/square/'
    | '/tasks/'
    | '/template/'
    | '/validate/'
    | '/visual/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/manualUpload'
    | '/models/square'
    | '/slices/create'
    | '/square/create'
    | '/system/user'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/template/$templateId'
    | '/template/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/visual/$modelId'
    | '/datasets'
    | '/models'
    | '/monitor'
    | '/slices'
    | '/square'
    | '/tasks'
    | '/template'
    | '/validate'
    | '/visual'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/manualUpload'
    | '/models/square'
    | '/slices/create'
    | '/square/create'
    | '/system/user'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/template/$templateId'
    | '/template/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/visual/$modelId'
    | '/datasets/'
    | '/models/'
    | '/monitor/'
    | '/slices/'
    | '/square/'
    | '/tasks/'
    | '/template/'
    | '/validate/'
    | '/visual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ModelsManualUploadRoute: typeof ModelsManualUploadRoute
  ModelsSquareRoute: typeof ModelsSquareRoute
  SlicesCreateRoute: typeof SlicesCreateRoute
  SquareCreateRoute: typeof SquareCreateRoute
  SystemUserRoute: typeof SystemUserRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCreateRoute: typeof TasksCreateRoute
  TemplateTemplateIdRoute: typeof TemplateTemplateIdRoute
  TemplateCreateRoute: typeof TemplateCreateRoute
  ValidateTaskIdRoute: typeof ValidateTaskIdRoute
  ValidateCreateRoute: typeof ValidateCreateRoute
  VisualModelIdRoute: typeof VisualModelIdRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  MonitorIndexRoute: typeof MonitorIndexRoute
  SlicesIndexRoute: typeof SlicesIndexRoute
  SquareIndexRoute: typeof SquareIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TemplateIndexRoute: typeof TemplateIndexRoute
  ValidateIndexRoute: typeof ValidateIndexRoute
  VisualIndexRoute: typeof VisualIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/': {
      id: '/visual/'
      path: '/visual'
      fullPath: '/visual/'
      preLoaderRoute: typeof VisualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/': {
      id: '/validate/'
      path: '/validate'
      fullPath: '/validate/'
      preLoaderRoute: typeof ValidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/': {
      id: '/template/'
      path: '/template'
      fullPath: '/template/'
      preLoaderRoute: typeof TemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/square/': {
      id: '/square/'
      path: '/square'
      fullPath: '/square/'
      preLoaderRoute: typeof SquareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slices/': {
      id: '/slices/'
      path: '/slices'
      fullPath: '/slices/'
      preLoaderRoute: typeof SlicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/': {
      id: '/monitor/'
      path: '/monitor'
      fullPath: '/monitor/'
      preLoaderRoute: typeof MonitorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/$modelId': {
      id: '/visual/$modelId'
      path: '/visual/$modelId'
      fullPath: '/visual/$modelId'
      preLoaderRoute: typeof VisualModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/create': {
      id: '/validate/create'
      path: '/validate/create'
      fullPath: '/validate/create'
      preLoaderRoute: typeof ValidateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/$taskId': {
      id: '/validate/$taskId'
      path: '/validate/$taskId'
      fullPath: '/validate/$taskId'
      preLoaderRoute: typeof ValidateTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/create': {
      id: '/template/create'
      path: '/template/create'
      fullPath: '/template/create'
      preLoaderRoute: typeof TemplateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$templateId': {
      id: '/template/$templateId'
      path: '/template/$templateId'
      fullPath: '/template/$templateId'
      preLoaderRoute: typeof TemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/user': {
      id: '/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof SystemUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/square/create': {
      id: '/square/create'
      path: '/square/create'
      fullPath: '/square/create'
      preLoaderRoute: typeof SquareCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slices/create': {
      id: '/slices/create'
      path: '/slices/create'
      fullPath: '/slices/create'
      preLoaderRoute: typeof SlicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/square': {
      id: '/models/square'
      path: '/models/square'
      fullPath: '/models/square'
      preLoaderRoute: typeof ModelsSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/manualUpload': {
      id: '/models/manualUpload'
      path: '/models/manualUpload'
      fullPath: '/models/manualUpload'
      preLoaderRoute: typeof ModelsManualUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ModelsManualUploadRoute: ModelsManualUploadRoute,
  ModelsSquareRoute: ModelsSquareRoute,
  SlicesCreateRoute: SlicesCreateRoute,
  SquareCreateRoute: SquareCreateRoute,
  SystemUserRoute: SystemUserRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCreateRoute: TasksCreateRoute,
  TemplateTemplateIdRoute: TemplateTemplateIdRoute,
  TemplateCreateRoute: TemplateCreateRoute,
  ValidateTaskIdRoute: ValidateTaskIdRoute,
  ValidateCreateRoute: ValidateCreateRoute,
  VisualModelIdRoute: VisualModelIdRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  MonitorIndexRoute: MonitorIndexRoute,
  SlicesIndexRoute: SlicesIndexRoute,
  SquareIndexRoute: SquareIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TemplateIndexRoute: TemplateIndexRoute,
  ValidateIndexRoute: ValidateIndexRoute,
  VisualIndexRoute: VisualIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
