/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidateIndexRouteImport } from './routes/validate/index'
import { Route as TrainIndexRouteImport } from './routes/train/index'
import { Route as TemplateIndexRouteImport } from './routes/template/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SplitIndexRouteImport } from './routes/split/index'
import { Route as MonitorIndexRouteImport } from './routes/monitor/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ValidateCreateRouteImport } from './routes/validate/create'
import { Route as ValidateTaskIdRouteImport } from './routes/validate/$taskId'
import { Route as TrainCreateRouteImport } from './routes/train/create'
import { Route as TrainTaskIdRouteImport } from './routes/train/$taskId'
import { Route as TemplateCreateRouteImport } from './routes/template/create'
import { Route as TemplateTemplateIdRouteImport } from './routes/template/$templateId'
import { Route as TasksCreateRouteImport } from './routes/tasks/create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SystemUserRouteImport } from './routes/system/user'
import { Route as SplitCreateRouteImport } from './routes/split/create'
import { Route as ModelsManualUploadRouteImport } from './routes/models/manualUpload'
import { Route as ModelsCreateRouteImport } from './routes/models/create'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateIndexRoute = ValidateIndexRouteImport.update({
  id: '/validate/',
  path: '/validate/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainIndexRoute = TrainIndexRouteImport.update({
  id: '/train/',
  path: '/train/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIndexRoute = TemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitIndexRoute = SplitIndexRouteImport.update({
  id: '/split/',
  path: '/split/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIndexRoute = MonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateCreateRoute = ValidateCreateRouteImport.update({
  id: '/validate/create',
  path: '/validate/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateTaskIdRoute = ValidateTaskIdRouteImport.update({
  id: '/validate/$taskId',
  path: '/validate/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainCreateRoute = TrainCreateRouteImport.update({
  id: '/train/create',
  path: '/train/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainTaskIdRoute = TrainTaskIdRouteImport.update({
  id: '/train/$taskId',
  path: '/train/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateCreateRoute = TemplateCreateRouteImport.update({
  id: '/template/create',
  path: '/template/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateTemplateIdRoute = TemplateTemplateIdRouteImport.update({
  id: '/template/$templateId',
  path: '/template/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUserRoute = SystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitCreateRoute = SplitCreateRouteImport.update({
  id: '/split/create',
  path: '/split/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsManualUploadRoute = ModelsManualUploadRouteImport.update({
  id: '/models/manualUpload',
  path: '/models/manualUpload',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCreateRoute = ModelsCreateRouteImport.update({
  id: '/models/create',
  path: '/models/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/create': typeof ModelsCreateRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/split/create': typeof SplitCreateRoute
  '/system/user': typeof SystemUserRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/template/create': typeof TemplateCreateRoute
  '/train/$taskId': typeof TrainTaskIdRoute
  '/train/create': typeof TrainCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/split/': typeof SplitIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/template/': typeof TemplateIndexRoute
  '/train/': typeof TrainIndexRoute
  '/validate/': typeof ValidateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/create': typeof ModelsCreateRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/split/create': typeof SplitCreateRoute
  '/system/user': typeof SystemUserRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/template/create': typeof TemplateCreateRoute
  '/train/$taskId': typeof TrainTaskIdRoute
  '/train/create': typeof TrainCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/datasets': typeof DatasetsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/monitor': typeof MonitorIndexRoute
  '/split': typeof SplitIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/template': typeof TemplateIndexRoute
  '/train': typeof TrainIndexRoute
  '/validate': typeof ValidateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/create': typeof ModelsCreateRoute
  '/models/manualUpload': typeof ModelsManualUploadRoute
  '/split/create': typeof SplitCreateRoute
  '/system/user': typeof SystemUserRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/template/create': typeof TemplateCreateRoute
  '/train/$taskId': typeof TrainTaskIdRoute
  '/train/create': typeof TrainCreateRoute
  '/validate/$taskId': typeof ValidateTaskIdRoute
  '/validate/create': typeof ValidateCreateRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/split/': typeof SplitIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/template/': typeof TemplateIndexRoute
  '/train/': typeof TrainIndexRoute
  '/validate/': typeof ValidateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/create'
    | '/models/manualUpload'
    | '/split/create'
    | '/system/user'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/template/$templateId'
    | '/template/create'
    | '/train/$taskId'
    | '/train/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/datasets/'
    | '/models/'
    | '/monitor/'
    | '/split/'
    | '/tasks/'
    | '/template/'
    | '/train/'
    | '/validate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/create'
    | '/models/manualUpload'
    | '/split/create'
    | '/system/user'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/template/$templateId'
    | '/template/create'
    | '/train/$taskId'
    | '/train/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/datasets'
    | '/models'
    | '/monitor'
    | '/split'
    | '/tasks'
    | '/template'
    | '/train'
    | '/validate'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/datasets/$datasetId'
    | '/models/$modelId'
    | '/models/create'
    | '/models/manualUpload'
    | '/split/create'
    | '/system/user'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/template/$templateId'
    | '/template/create'
    | '/train/$taskId'
    | '/train/create'
    | '/validate/$taskId'
    | '/validate/create'
    | '/datasets/'
    | '/models/'
    | '/monitor/'
    | '/split/'
    | '/tasks/'
    | '/template/'
    | '/train/'
    | '/validate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ModelsCreateRoute: typeof ModelsCreateRoute
  ModelsManualUploadRoute: typeof ModelsManualUploadRoute
  SplitCreateRoute: typeof SplitCreateRoute
  SystemUserRoute: typeof SystemUserRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCreateRoute: typeof TasksCreateRoute
  TemplateTemplateIdRoute: typeof TemplateTemplateIdRoute
  TemplateCreateRoute: typeof TemplateCreateRoute
  TrainTaskIdRoute: typeof TrainTaskIdRoute
  TrainCreateRoute: typeof TrainCreateRoute
  ValidateTaskIdRoute: typeof ValidateTaskIdRoute
  ValidateCreateRoute: typeof ValidateCreateRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  MonitorIndexRoute: typeof MonitorIndexRoute
  SplitIndexRoute: typeof SplitIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TemplateIndexRoute: typeof TemplateIndexRoute
  TrainIndexRoute: typeof TrainIndexRoute
  ValidateIndexRoute: typeof ValidateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/': {
      id: '/validate/'
      path: '/validate'
      fullPath: '/validate/'
      preLoaderRoute: typeof ValidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/': {
      id: '/train/'
      path: '/train'
      fullPath: '/train/'
      preLoaderRoute: typeof TrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/': {
      id: '/template/'
      path: '/template'
      fullPath: '/template/'
      preLoaderRoute: typeof TemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/': {
      id: '/split/'
      path: '/split'
      fullPath: '/split/'
      preLoaderRoute: typeof SplitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/': {
      id: '/monitor/'
      path: '/monitor'
      fullPath: '/monitor/'
      preLoaderRoute: typeof MonitorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/create': {
      id: '/validate/create'
      path: '/validate/create'
      fullPath: '/validate/create'
      preLoaderRoute: typeof ValidateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/$taskId': {
      id: '/validate/$taskId'
      path: '/validate/$taskId'
      fullPath: '/validate/$taskId'
      preLoaderRoute: typeof ValidateTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/create': {
      id: '/train/create'
      path: '/train/create'
      fullPath: '/train/create'
      preLoaderRoute: typeof TrainCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$taskId': {
      id: '/train/$taskId'
      path: '/train/$taskId'
      fullPath: '/train/$taskId'
      preLoaderRoute: typeof TrainTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/create': {
      id: '/template/create'
      path: '/template/create'
      fullPath: '/template/create'
      preLoaderRoute: typeof TemplateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$templateId': {
      id: '/template/$templateId'
      path: '/template/$templateId'
      fullPath: '/template/$templateId'
      preLoaderRoute: typeof TemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/user': {
      id: '/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof SystemUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/create': {
      id: '/split/create'
      path: '/split/create'
      fullPath: '/split/create'
      preLoaderRoute: typeof SplitCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/manualUpload': {
      id: '/models/manualUpload'
      path: '/models/manualUpload'
      fullPath: '/models/manualUpload'
      preLoaderRoute: typeof ModelsManualUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/create': {
      id: '/models/create'
      path: '/models/create'
      fullPath: '/models/create'
      preLoaderRoute: typeof ModelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ModelsCreateRoute: ModelsCreateRoute,
  ModelsManualUploadRoute: ModelsManualUploadRoute,
  SplitCreateRoute: SplitCreateRoute,
  SystemUserRoute: SystemUserRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCreateRoute: TasksCreateRoute,
  TemplateTemplateIdRoute: TemplateTemplateIdRoute,
  TemplateCreateRoute: TemplateCreateRoute,
  TrainTaskIdRoute: TrainTaskIdRoute,
  TrainCreateRoute: TrainCreateRoute,
  ValidateTaskIdRoute: ValidateTaskIdRoute,
  ValidateCreateRoute: ValidateCreateRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  MonitorIndexRoute: MonitorIndexRoute,
  SplitIndexRoute: SplitIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TemplateIndexRoute: TemplateIndexRoute,
  TrainIndexRoute: TrainIndexRoute,
  ValidateIndexRoute: ValidateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
